name: Validate Homey App
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:  
    main:
      name: Validate Homey App
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js '18.x'
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified

      - name: Publish
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}
      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
